
PRAGMA foreign_keys = ON;

CREATE TABLE CUSTOMER (
 CUSTOMER_ID CHAR(5) PRIMARY KEY,
 CUS_NAME VARCHAR(100) NOT NULL,
 CUS_HOUSE_NO VARCHAR(20) NOT NULL,
 CUS_STREET VARCHAR(100),
 CUS_SUBDISTRICT VARCHAR(100),
 CUS_DISTRICT VARCHAR(100),
 CUS_PROVINCE VARCHAR(100),
 CUS_POSTCODE VARCHAR(10),
 CUS_PHONE VARCHAR(20)
);

CREATE TABLE DEVICE (
 DEVICE_ID CHAR(5) PRIMARY KEY,
 CUSTOMER_ID CHAR(5) NOT NULL,
 DEVICE_TYPE VARCHAR(50) NOT NULL,
 BRAND VARCHAR(50) NOT NULL,
 MODEL VARCHAR(50),
 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE TECHNICIAN (
 TECH_ID CHAR(5) PRIMARY KEY,
 TECH_NAME VARCHAR(100) NOT NULL,
 TECH_SPECIALTY VARCHAR(100)
);

CREATE TABLE SYMPTOM (
 SYMPTOM_ID CHAR(5) PRIMARY KEY,
 SYMPTOM_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE SPARE_PART (
 PART_ID CHAR(5) PRIMARY KEY,
 PART_NAME VARCHAR(100) NOT NULL,
 PART_PRICE DECIMAL(8,2) NOT NULL DEFAULT 0,
 STOCK_QTY INT NOT NULL DEFAULT 0
);

CREATE TABLE SUPPLIER (
 SUPPLIER_ID CHAR(5) PRIMARY KEY,
 SUPPLIER_NAME VARCHAR(100) NOT NULL,
 SUPPLIER_PHONE VARCHAR(20)
);

CREATE TABLE REPAIR_ORDER (
 ORDER_ID CHAR(6) PRIMARY KEY,
 DEVICE_ID CHAR(5) NOT NULL,
 TECH_ID CHAR(5) NOT NULL,
 DATE_RECEIVED DATE NOT NULL,
 DATE_COMPLETED DATE,
 LABOR_COST DECIMAL(8,2) NOT NULL DEFAULT 0,
 FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE(DEVICE_ID),
 FOREIGN KEY (TECH_ID) REFERENCES TECHNICIAN(TECH_ID)
);

CREATE TABLE REPAIR_SYMPTOM (
 ORDER_ID CHAR(6) NOT NULL,
 SYMPTOM_ID CHAR(5) NOT NULL,
 PRIMARY KEY (ORDER_ID, SYMPTOM_ID),
 FOREIGN KEY (ORDER_ID) REFERENCES REPAIR_ORDER(ORDER_ID),
 FOREIGN KEY (SYMPTOM_ID) REFERENCES SYMPTOM(SYMPTOM_ID)
);

CREATE TABLE REPAIR_PART_USED (
 ORDER_ID CHAR(6) NOT NULL,
 PART_ID CHAR(5) NOT NULL,
 QTY_USED INT NOT NULL DEFAULT 1,
 PRIMARY KEY (ORDER_ID, PART_ID),
 FOREIGN KEY (ORDER_ID) REFERENCES REPAIR_ORDER(ORDER_ID),
 FOREIGN KEY (PART_ID) REFERENCES SPARE_PART(PART_ID)
);

CREATE TABLE PAYMENT (
 PAYMENT_ID CHAR(6) PRIMARY KEY,
 ORDER_ID CHAR(6) NOT NULL UNIQUE,
 PAYMENT_METHOD VARCHAR(20) NOT NULL,
 PAYMENT_AMOUNT DECIMAL(8,2) NOT NULL,
 PAYMENT_STATUS VARCHAR(20) NOT NULL DEFAULT 'รอชำระ',
 PAYMENT_DATE DATE,
 FOREIGN KEY (ORDER_ID) REFERENCES REPAIR_ORDER(ORDER_ID)
);

CREATE TABLE STOCK_MOVEMENT (
 MOVEMENT_ID CHAR(6) PRIMARY KEY,
 PART_ID CHAR(5) NOT NULL,
 SUPPLIER_ID CHAR(5),
 MOVEMENT_TYPE VARCHAR(10) NOT NULL,
 MOVEMENT_QTY INT NOT NULL,
 MOVEMENT_DATE DATE NOT NULL,
 FOREIGN KEY (PART_ID) REFERENCES SPARE_PART(PART_ID),
 FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID)
);
